# Generated by Django 4.0.5 on 2022-06-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuxPizzas', '0002_delete_empanadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='tamanio',
            field=models.CharField(choices=[('1', 'Individual'), ('2', 'Grande'), ('3', 'Familiar')], default='Individual', max_length=20),
        ),
    ]
