# Generated by Django 4.0.5 on 2022-06-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuxPizzas', '0003_alter_pizzas_tamanio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='foto',
            field=models.CharField(default=1, max_length=9999999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='tamanio',
            field=models.CharField(choices=[('1', 'Individual'), ('2', 'Grande'), ('3', 'Familiar')], max_length=20),
        ),
    ]
