# Generated by Django 4.0.5 on 2022-06-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuxPizzas', '0004_pizzas_foto_alter_pizzas_tamanio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empanadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('foto', models.CharField(max_length=9999999)),
                ('relleno', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hamburguesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('foto', models.CharField(max_length=9999999)),
                ('ingredientes', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
